name: Deploy Node Application

on:
  push: 
    branches: 
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t gabriellelu/fitness-tracker-backend .
      - name: Publish Image to docker hub
        run: docker push gabriellelu/fitness-tracker-backend:latest

  deploy: 
    needs: build 
    runs-on: self-hosted
    steps: 
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull image from docker hub
        run: docker pull gabriellelu/fitness-tracker-backend:latest
      - name: Delete old container
        run: docker rm -f nodejs-app-container
      - name: Run Docker Container
        run: docker run -d -p 8080:8080 --name nodejs-app-container -e gabriellelu/fitness-tracker-backend



